#!/usr/bin/env bash

### Documentation
### https://wiki.samba.org/index.php/Setting_up_Samba_as_an_Active_Directory_Domain_Controller

# Exit if any error
set -euo pipefail

# Skip domain provision if secrets exists
if [[ ! -e "${SAMBA_PATH:-/var/lib/samba}/private/secrets.keytab" ]]; then

  # Wait for network interface
  until ip a | grep BROADCAST >/dev/null 2>&1; do
    echo "Waiting for network interface.."
    sleep 1
  done

  INTERFACE=$(ip a | grep BROADCAST | head -n1 | awk '{print $2}' | sed 's/://')

  samba-tool domain provision \
    --server-role="${SERVER_ROLE:-dc}" \
    --use-rfc2307 \
    --dns-backend="${DNS_BACKEND:-SAMBA_INTERNAL}" \
    --realm="${REALM}" \
    --domain="${DOMAIN}" \
    --adminpass="${ADMIN_PASS}" \
    --option="dns forwarder=${DNS_FORWARDER}"

fi

update-etc-files

service samba-ad-dc start
service --status-all

#  [ - ]  cron
#  [ - ]  dbus
#  [ ? ]  hwclock.sh
#  [ - ]  nmbd
#  [ - ]  procps
#  [ + ]  samba-ad-dc
#  [ + ]  smbd
#  [ - ]  winbind