FROM httpd:2.4-bullseye

# Install samba, kerberos and required utils
RUN apt update && apt upgrade -y && \
  DEBIAN_FRONTEND=noninteractive \
  apt install \
    samba \
    krb5-user \
    netcat iputils-ping iproute2 -y

# Install some dev-useful tools
RUN apt install mc tmux less vim -y

# clean up
RUN apt clean autoclean \
  && apt autoremove -y

# TODO find a better solution
# Copy krb5.conf before it will be done by 'update-etc-files' script
# RUN mkdir -p /var/lib/samba/private/ \
#     && cp /etc/krb5.conf /var/lib/samba/private/

# Copy samba scripts
RUN mkdir -p /usr/local/sbin
COPY samba-utils /usr/local/sbin
WORKDIR /usr/local/sbin